README.md, app/Http/Controllers/WebpayController.php, app/Http/Controllers/WebpayPlusMallController.php, resources/css/app.css, resources/views/components/menu.blade.php, resources/views/webpay-mall/commit.blade.php, resources/views/webpay-mall/create.blade.php, resources/views/webpay-mall/refund.blade.php, resources/views/webpay-mall/status.blade.php, routes/web.php
=> feat: webpay mall

app/Http/Controllers/WebpayPlusDeferredController.php, resources/views/components/menu.blade.php, resources/views/webpay-deferred/capture.blade.php, resources/views/webpay-deferred/commit.blade.php, resources/views/webpay-deferred/create.blade.php, resources/views/webpay-deferred/refund.blade.php, resources/views/webpay-deferred/status.blade.php, resources/views/webpay-mall/commit.blade.php, resources/views/webpay-mall/create.blade.php, resources/views/webpay-mall/refund.blade.php, resources/views/webpay-mall/status.blade.php, resources/views/webpay/commit.blade.php, resources/views/webpay/create.blade.php, resources/views/webpay/refund.blade.php, resources/views/webpay/status.blade.php, routes/web.php
=> Feat: webpay deferred

.github/workflows/build.yml
This PR add Sonar Cloud scan to CI flow
=> chore: add sonar cloud

app/Http/Controllers/OneclickMallDeferredController.php, resources/views/components/menu.blade.php, resources/views/oneclick-mall-deferred/authorize.blade.php, resources/views/oneclick-mall-deferred/capture.blade.php, resources/views/oneclick-mall-deferred/delete.blade.php, resources/views/oneclick-mall-deferred/finish.blade.php, resources/views/oneclick-mall-deferred/recoverTransaction.blade.php, resources/views/oneclick-mall-deferred/refund.blade.php, resources/views/oneclick-mall-deferred/rejected.blade.php, resources/views/oneclick-mall-deferred/start.blade.php, resources/views/oneclick-mall-deferred/status.blade.php, resources/views/oneclick-mall-deferred/timeout.blade.php, resources/views/oneclick-mall/finish.blade.php, resources/views/oneclick-mall/start.blade.php, resources/views/webpay-mall-deferred/capture.blade.php, resources/views/webpay-mall-deferred/create.blade.php, routes/web.php
=> feat: oneclick deferred

app/Http/Controllers/WebpayController.php, app/Http/Controllers/WebpayPlusDeferredController.php, app/Http/Controllers/WebpayPlusMallController.php, app/Http/Controllers/WebpayPlusMallDeferredController.php
This PR add a random number to buy order on create method. Now refunds can be donde without errors.
=> feat: improve operation flow

resources/views/oneclick-mall-deferred/recoverTransaction.blade.php, resources/views/oneclick-mall-deferred/refund.blade.php, resources/views/oneclick-mall-deferred/start.blade.php, resources/views/oneclick-mall/recoverTransaction.blade.php, resources/views/oneclick-mall/refund.blade.php, resources/views/oneclick-mall/start.blade.php, resources/views/webpay-deferred/commit.blade.php, resources/views/webpay-deferred/create.blade.php, resources/views/webpay-deferred/refund.blade.php, resources/views/webpay-mall-deferred/commit.blade.php, resources/views/webpay-mall-deferred/create.blade.php, resources/views/webpay-mall-deferred/refund.blade.php, resources/views/webpay-mall/commit.blade.php, resources/views/webpay-mall/create.blade.php, resources/views/webpay-mall/refund.blade.php, resources/views/webpay/commit.blade.php, resources/views/webpay/create.blade.php, resources/views/webpay/refund.blade.php
The texts are updated with the latest changes.
=> feat: add missing texts

resources/views/components/menu.blade.php, resources/views/home.blade.php
This PR remove references to _PatPass_ and _Transacción completa_ since these products are not implemented yet.
=> feat: remove references to unimplemented products

resources/css/app.css, resources/views/webpay-deferred/capture.blade.php, resources/views/webpay-mall-deferred/capture.blade.php, resources/views/webpay/commit.blade.php
This PR relocate status button alongside the refund button when necessary.
=> feat: relocate status button

.github/workflows/build.yml, sonar-project.properties
=> chore:  fix ci

app/Http/Controllers/OneclickMallController.php, app/Http/Controllers/OneclickMallDeferredController.php, app/Http/Controllers/WebpayController.php, app/Http/Controllers/WebpayPlusDeferredController.php, app/Http/Controllers/WebpayPlusMallController.php, resources/views/oneclick-mall-deferred/capture.blade.php, resources/views/oneclick-mall-deferred/refund.blade.php, resources/views/oneclick-mall/refund.blade.php, resources/views/webpay-deferred/refund.blade.php, resources/views/webpay-mall-deferred/refund.blade.php, resources/views/webpay-mall/refund.blade.php, resources/views/webpay/refund.blade.php
This PR add status button on refund views for all products.
=> feat: add status button

app/Http/Controllers/WebpayController.php, bootstrap/app.php, package-lock.json, resources/views/webpay/error/aborted.blade.php, resources/views/webpay/error/form-error.blade.php, resources/views/webpay/error/timeout.blade.php, routes/web.php
This PR add the error flow pages for Webpay Plus.
=> feat: add error flows page for Webpay Plus

app/Http/Controllers/OneclickMallController.php, app/Http/Controllers/OneclickMallDeferredController.php, resources/css/app.css, resources/views/oneclick-mall-deferred/finish.blade.php, resources/views/oneclick-mall/finish.blade.php, routes/web.php
This PR add an authorization form for oneclick and oneclick deferred. Now user can set amount and installments values.
=> feat: oneclick authorize form

resources/views/oneclick-mall-deferred/delete.blade.php, resources/views/oneclick-mall/delete.blade.php
This PR update description for delete response
=> fix: delete inscription text

app/Http/Controllers/OneclickMallController.php, app/Http/Controllers/OneclickMallDeferredController.php, app/Http/Controllers/WebpayController.php, app/Http/Controllers/WebpayPlusDeferredController.php, app/Http/Controllers/WebpayPlusMallController.php, app/Http/Controllers/WebpayPlusMallDeferredController.php
This PR get credentials from environment to use on controllers
=> refactor: get credentials from environment on controllers

package-lock.json, resources/views/oneclick-mall-deferred/capture.blade.php, resources/views/oneclick-mall/authorize.blade.php, resources/views/webpay-deferred/capture.blade.php, resources/views/webpay-mall-deferred/capture.blade.php, resources/views/webpay-mall/commit.blade.php, resources/views/webpay/commit.blade.php, routes/web.php
This PR change method to GET for refund operations.
=> feat: use get for refunds

app/Http/Controllers/WebpayController.php, app/Http/Controllers/WebpayPlusDeferredController.php, app/Http/Controllers/WebpayPlusMallController.php, app/Http/Controllers/WebpayPlusMallDeferredController.php, resources/views/error/webpay/aborted.blade.php, resources/views/error/webpay/form-error.blade.php, resources/views/error/webpay/timeout.blade.php
This PR handles error views for webpay plus flows
=> feat: handle webpay error views

app/Http/Controllers/OneclickMallController.php, app/Http/Controllers/OneclickMallDeferredController.php, app/Http/Controllers/WebpayController.php, app/Http/Controllers/WebpayPlusDeferredController.php, app/Http/Controllers/WebpayPlusMallController.php, app/Http/Controllers/WebpayPlusMallDeferredController.php, resources/views/components/layout.blade.php, resources/views/components/navigation.blade.php, resources/views/error-page.blade.php
This PR add the error page for all operations.
=> feat: add error page

resources/views/webpay-deferred/create.blade.php, resources/views/webpay-mall/create.blade.php, resources/views/webpay/create.blade.php
This PR add missing text on webpay plus create views
=> feat: add missing text in webpay plus create views

resources/views/oneclick-mall-deferred/authorize.blade.php, resources/views/webpay-deferred/commit.blade.php, resources/views/webpay-mall-deferred/commit.blade.php, routes/web.php
This PR change method to GET for capture operations.
=> feat: change method to get for capture operations

CHANGELOG.md, README.md
=> release: prepare release 1.0.0

app/Http/Controllers/WebpayController.php, config/webpayParams.php, package-lock.json, resources/css/app.css, resources/views/components/TableObject.blade.php, resources/views/components/collapse.blade.php, resources/views/components/layout.blade.php, resources/views/components/menu.blade.php, resources/views/components/snippet.blade.php, resources/views/webpay/api-operations.blade.php, routes/web.php
=> feat: api operations webpay plus

app/Livewire/Webpay/Refund.php, app/Livewire/Webpay/Status.php, resources/css/app.css, resources/js/app.js, resources/views/livewire/webpay/refund.blade.php, resources/views/livewire/webpay/status.blade.php, resources/views/webpay/api-operations.blade.php, vite.config.js
=> feat: async forms

app/Http/Controllers/WebpayController.php, app/Http/Controllers/WebpayPlusDeferredController.php, app/Livewire/Webpay/Refund.php, app/Livewire/Webpay/Status.php, app/Livewire/WebpayDeferred/Capture.php, app/Livewire/WebpayDeferred/Refund.php, app/Livewire/WebpayDeferred/Status.php, config/webpayParams.php, resources/views/components/menu.blade.php, resources/views/livewire/webpay-deferred/capture.blade.php, resources/views/livewire/webpay-deferred/refund.blade.php, resources/views/livewire/webpay-deferred/status.blade.php, resources/views/webpay-deferred/api-operations.blade.php, routes/web.php
=> Feat: api operation webpay deferred

app/Http/Controllers/WebpayPlusMallController.php, app/Livewire/WebpayMall/Refund.php, app/Livewire/WebpayMall/Status.php, resources/views/components/menu.blade.php, resources/views/livewire/webpay-mall/refund.blade.php, resources/views/livewire/webpay-mall/status.blade.php, resources/views/webpay-deferred/api-operations.blade.php, resources/views/webpay-mall/api-operations.blade.php, resources/views/webpay/api-operations.blade.php
=> feat: webpay mall op

app/Http/Controllers/OneclickMallController.php, app/Livewire/OneclickMall/Authorize.php, app/Livewire/OneclickMall/Refund.php, app/Livewire/OneclickMall/Status.php, resources/css/app.css, resources/views/components/menu.blade.php, resources/views/components/mobileMenu.blade.php, resources/views/livewire/oneclick-mall/authorize.blade.php, resources/views/livewire/oneclick-mall/refund.blade.php, resources/views/livewire/oneclick-mall/status.blade.php, resources/views/oneclick-mall/api-operations.blade.php
add api operation view for onclick mall
=> Feat: onclick mall op

app/Http/Controllers/OneclickMallDeferredController.php, app/Livewire/OneclickMall/Authorize.php, app/Livewire/OneclickMallDeferred/Authorize.php, app/Livewire/OneclickMallDeferred/Capture.php, app/Livewire/OneclickMallDeferred/Refund.php, app/Livewire/OneclickMallDeferred/Status.php, config/webpayParams.php, resources/views/components/menu.blade.php, resources/views/components/mobileMenu.blade.php, resources/views/livewire/oneclick-mall-deferred/authorize.blade.php, resources/views/livewire/oneclick-mall-deferred/capture.blade.php, resources/views/livewire/oneclick-mall-deferred/refund.blade.php, resources/views/livewire/oneclick-mall-deferred/status.blade.php, resources/views/oneclick-mall-deferred/api-operations.blade.php
add api operation view for oneclick mall deferred
=> Feat: oneclick mall deferred op
